-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-11-16 22:46:08 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE address CASCADE CONSTRAINTS;

DROP TABLE client CASCADE CONSTRAINTS;

DROP TABLE coverage CASCADE CONSTRAINTS;

DROP TABLE coveragegroup CASCADE CONSTRAINTS;

DROP TABLE employee CASCADE CONSTRAINTS;

DROP TABLE feature CASCADE CONSTRAINTS;

DROP TABLE feature_coverage CASCADE CONSTRAINTS;

DROP TABLE insurance CASCADE CONSTRAINTS;

DROP TABLE phone CASCADE CONSTRAINTS;

DROP TABLE phonetype CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    address_id     INTEGER NOT NULL,
    country        VARCHAR2(50) NOT NULL,
    region         VARCHAR2(50) NOT NULL,
    city           VARCHAR2(50) NOT NULL,
    street         VARCHAR2(50) NOT NULL,
    address_number INTEGER NOT NULL
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE client (
    client_id     INTEGER NOT NULL,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    address_id    INTEGER NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( client_id );

CREATE TABLE coverage (
    coverage_id      INTEGER NOT NULL,
    coverage_name    VARCHAR2(50) NOT NULL,
    description      VARCHAR2(200),
    coveragegroup_id INTEGER NOT NULL
);

ALTER TABLE coverage ADD CONSTRAINT coverage_pk PRIMARY KEY ( coverage_id );

CREATE TABLE coveragegroup (
    coveragegroup_id   INTEGER NOT NULL,
    coveragegroup_name VARCHAR2(50) NOT NULL
);

ALTER TABLE coveragegroup ADD CONSTRAINT coveragegroup_pk PRIMARY KEY ( coveragegroup_id );

CREATE TABLE employee (
    employee_id   INTEGER NOT NULL,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    address_id    INTEGER NOT NULL
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE feature (
    feature_id       INTEGER NOT NULL,
    feature_name     VARCHAR2(50) NOT NULL,
    coveragegroup_id INTEGER NOT NULL
);

ALTER TABLE feature ADD CONSTRAINT feature_pk PRIMARY KEY ( feature_id );

CREATE TABLE feature_coverage (
    feature_coverage_id INTEGER NOT NULL,
    coverage_id         INTEGER NOT NULL,
    feature_id          INTEGER NOT NULL
);

ALTER TABLE feature_coverage ADD CONSTRAINT feature_coverage_pk PRIMARY KEY ( feature_coverage_id );

CREATE TABLE insurance (
    insurance_id     INTEGER NOT NULL,
    insurance_number VARCHAR2(50) NOT NULL,
    client_id        INTEGER NOT NULL,
    employee_id      INTEGER NOT NULL,
    begin_date       DATE NOT NULL,
    expiration_date  DATE NOT NULL,
    coverage_id      INTEGER NOT NULL
);

ALTER TABLE insurance ADD CONSTRAINT insurance_pk PRIMARY KEY ( insurance_id );

CREATE TABLE phone (
    phone_id     INTEGER NOT NULL,
    phone_number VARCHAR2(15) NOT NULL,
    client_id    INTEGER,
    phonetype_id INTEGER NOT NULL,
    employee_id  INTEGER
);

ALTER TABLE phone ADD CONSTRAINT phone_pk PRIMARY KEY ( phone_id );

CREATE TABLE phonetype (
    phonetype_id INTEGER NOT NULL,
    type_name    VARCHAR2(50) NOT NULL
);

ALTER TABLE phonetype ADD CONSTRAINT phonetype_pk PRIMARY KEY ( phonetype_id );

ALTER TABLE client
    ADD CONSTRAINT client_address_fk FOREIGN KEY ( address_id )
        REFERENCES address ( address_id )
            ON DELETE CASCADE;

ALTER TABLE coverage
    ADD CONSTRAINT coverage_coveragegroup_fk FOREIGN KEY ( coveragegroup_id )
        REFERENCES coveragegroup ( coveragegroup_id )
            ON DELETE CASCADE;

ALTER TABLE employee
    ADD CONSTRAINT employee_address_fk FOREIGN KEY ( address_id )
        REFERENCES address ( address_id )
            ON DELETE CASCADE;

ALTER TABLE feature_coverage
    ADD CONSTRAINT feature_coverage_coverage_fk FOREIGN KEY ( coverage_id )
        REFERENCES coverage ( coverage_id )
            ON DELETE CASCADE;

ALTER TABLE feature_coverage
    ADD CONSTRAINT feature_coverage_feature_fk FOREIGN KEY ( feature_id )
        REFERENCES feature ( feature_id );

ALTER TABLE feature
    ADD CONSTRAINT feature_coveragegroup_fk FOREIGN KEY ( coveragegroup_id )
        REFERENCES coveragegroup ( coveragegroup_id )
            ON DELETE CASCADE;

ALTER TABLE insurance
    ADD CONSTRAINT insurance_client_fk FOREIGN KEY ( client_id )
        REFERENCES client ( client_id )
            ON DELETE CASCADE;

ALTER TABLE insurance
    ADD CONSTRAINT insurance_coverage_fk FOREIGN KEY ( coverage_id )
        REFERENCES coverage ( coverage_id )
            ON DELETE CASCADE;

ALTER TABLE insurance
    ADD CONSTRAINT insurance_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id )
            ON DELETE CASCADE;

ALTER TABLE phone
    ADD CONSTRAINT phone_client_fk FOREIGN KEY ( client_id )
        REFERENCES client ( client_id )
            ON DELETE CASCADE;

ALTER TABLE phone
    ADD CONSTRAINT phone_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id )
            ON DELETE CASCADE;

ALTER TABLE phone
    ADD CONSTRAINT phone_phonetype_fk FOREIGN KEY ( phonetype_id )
        REFERENCES phonetype ( phonetype_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
