--------------------------------------------------------
--  File created - ¶roda-grudnia-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE" 
   (	"INSURANCE_ID" NUMBER(*,0), 
	"INSURANCE_NUMBER" VARCHAR2(50 BYTE), 
	"CLIENT_ID" NUMBER(*,0), 
	"EMPLOYEE_ID" NUMBER(*,0), 
	"BEGIN_DATE" DATE, 
	"EXPIRATION_DATE" DATE, 
	"INSURANCETYPE_ID" NUMBER(*,0), 
	"PAYMENT_ID" NUMBER(*,0), 
	"BRANCH_ID" NUMBER(*,0), 
	"PRICE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
/
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"REGION_ID" NUMBER(*,0), 
	"CITY_ID" NUMBER(*,0), 
	"STREET_ID" NUMBER(*,0), 
	"HOUSENR_ID" NUMBER(*,0), 
	"DATE_OF_EMPLOYMENT" DATE, 
	"SALARY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
/
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "CLIENT" 
   (	"CLIENT_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"REGION_ID" NUMBER(*,0), 
	"CITY_ID" NUMBER(*,0), 
	"STREET_ID" NUMBER(*,0), 
	"HOUSENR_ID" NUMBER(*,0), 
	"CLIENTTYPE_ID" NUMBER(*,0), 
	"DISCOUNT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
/
--------------------------------------------------------
--  DDL for Table CLAIM
--------------------------------------------------------

  CREATE TABLE "CLAIM" 
   (	"CLAIM_ID" NUMBER(*,0), 
	"CLAIM_NAME" VARCHAR2(50 BYTE), 
	"INSURANCE_ID" NUMBER(*,0), 
	"CLAIM_AMOUNT" NUMBER(*,0), 
	"CS_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
/
--------------------------------------------------------
--  DDL for Table BRANCH
--------------------------------------------------------

  CREATE TABLE "BRANCH" 
   (	"BRANCH_ID" NUMBER(*,0), 
	"BRANCH_NAME" VARCHAR2(50 BYTE), 
	"REGION_ID" NUMBER(*,0), 
	"CITY_ID" NUMBER(*,0), 
	"STREET_ID" NUMBER(*,0), 
	"HOUSENR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
/