sqlldr %1/%2@//localhost:1521/XEPDB1 control=region.ctl log=region.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=city.ctl log=city.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=street.ctl log=street.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=houseNr.ctl log=houseNr.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=clientType.ctl log=clientType.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=client.ctl log=client.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=employee.ctl log=employee.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=branch.ctl log=branch.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=phoneType.ctl log=phoneType.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=phone.ctl log=phone.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=payment.ctl log=payment.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=insuranceType.ctl log=insuranceType.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=insurance.ctl log=insurance.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=claimStatus.ctl log=claimStatus.log
sqlldr %1/%2@//localhost:1521/XEPDB1 control=claim.ctl log=claim.log